name: Release

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: '1.20.0'

      - name: Release
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} make release
